- name: Register microsoft key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
- name: package dpkg
  ansible.builtin.dpkg_selections:
    name: packages-microsoft-prod.deb
    selection: install
- name: Install apt transports
  ansible.builtin.package:
    name:
      - apt-transport-https
      - aspnetcore-runtime-7.0
      - zip
    update_cache: yes
    state: present
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Status nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
- name: copy the configuration file
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/
- name: create directory
  ansible.builtin.file:
    path: /var/www/nopCommerce
    state: directory
  notify:
    - changing ownership and group
- name: Download nopcommerce
  ansible.builtin.get_url:
    url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.3/nopCommerce_4.60.3_NoSource_linux_x64.zip
    dest: /var/www/nopCommerce
- name: Unzip nopcommerce
  ansible.builtin.unarchive:
    src: /var/www/nopCommerce/nopCommerce_4.60.3_NoSource_linux_x64.zip
    dest: /var/www/nopCommerce
    remote_src: yes
- notify:
    - restart nopcommerce
- name: Flush handlers
  meta: flush_handlers
- name: Create directory bin
  ansible.builtin.file:
    path: /var/www/nopcommerce/bin
    state: directory
- name: create directory logs
  ansible.builtin.file:
    path: /var/www/nopCommerce/logs
    state: directory
- name: nop commerce service file
  ansible.builtin.template:
    src: nop.service.j2
    dest: /etc/systemd/system/nop.service
    remote_src: no
- notify:
    - restart nopcommerce